name:                PasswordGen
version:             0.1.0.0
github:              "sa-mendez/PasswordGen"
license:             BSD3
author:              "Sergio Mendez"
maintainer:          "smendez_2000@yahoo.com"
copyright:           "2022 Sergio Mendez"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sa-smendez/PasswordGen#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- random
- mtl
- optparse-applicative
- extra
- text
- transformers

library:
  source-dirs: src

executables:
  PasswordGen-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PasswordGen

tests:
  PasswordGen-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PasswordGen
